import { useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';

import { Form } from '../components/Form';
import { Report } from '../components/Report';
import styles from '../styles/pages/Home.module.scss';

interface ICalculateProps {
  accountValue: number;
  paymentValue: number;
}

const Home: NextPage = () => {
  const [dados, setDados] = useState<ICalculateProps>({} as ICalculateProps);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form
          handleCalculate={(e, value, payment) => {
            e.preventDefault();
            setDados({ accountValue: value, paymentValue: payment });
          }}
        />

        {dados.accountValue && dados.paymentValue && (
          <Report
            accountValue={dados.accountValue}
            paymentValue={dados.paymentValue}
          />
        )}
      </main>
    </div>
  );
};

export default Home;
